name: m2-env
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.8.0
  - python=3.11.8
  - yaml=0.2.5
  - pip=23.3.1
  - pip:
      - torch==2.2.0
      - torchvision==0.17.0
      - tqdm==4.66.2
      - numpy==1.24.4
      - scipy==1.10.1
      - accelerate==0.27.2
      - ipykernel==6.29.2
      - ipython==8.21.0

