hyperparameters:
  seed: 12042000
  batch_size: 128
  num_workers: 8
  epochs: 100
  timesteps: [1000, 750, 500, 250, 100, 50, 10, 5, 1]
  interval: 7

CNN:
  in_channels: 1  
  expected_shape: [28, 28]
  n_hidden: [16, 32, 32, 16] 
  kernel_size: 7  
  last_kernel_size: 3  
  time_embeddings: 16  

ddpm:
  beta1: 1e-5
  beta2: 0.01
  n_T: 1000

optim:
  lr: 2e-4
  
